### ISSUE TITLE
Tổng hợp lỗi API 

### ISSUE THREAD

**Issue by longdratech** [dratech-team/minhdu-fontend#1013]
**Mô tả vấn đề mà bạn đang gặp phải**

_HR_
- [x] #1014
- [x] Lỗi thêm và cập nhật nhân viên seasonal thành công nhưng trả về vẫn là fulltime
- [x] search nhân viên theo phone chưa được
- [x] chưa search nhân viên theo identify( cmnd/cccd)
- [x] load payroll filtertype === OVERTIME thì trả về overtime trong overtimes(hiện tại đang trả vể trong salaries)
- [ ] load payroll fiterType === TIME_SHEET chưa trả về bảng chấm công
- [ ] thêm wfh bị lỗi
- [ ] Thêm tăng ca có phụ cấp thành công nhưng respone trả về ko có phụ cấp
- [ ] Cập nhật Bản mẫu Ngày lễ gửi lên list postion rỗng cập nhật thành công nhưng vẫn trả về chức vụ cũ tương tự branch

_SELL_

- [ ]  cập nhật lại hàng hoá trong chi tiết đơn hàng (histored === true) nhưng load lịch sửa chốt đơn của đơn hàng ko có
- [ ] Thống kê doanh thu theo tỉnh lỗi 500 "http://100.96.1.5:3000/v1/overview/sell?option=SALES&filter=NATION"

**Hành vi mong đợi**

**Đính kèm hình ảnh hoặc video**

**Comment by giahieu123456** [comment]
- [ ] Lỗi thêm và cập nhật nhân viên seasonal thành công nhưng trả về vẫn là fulltime

**Comment by giahieu123456** [comment]
- [ ]  search nhân viên theo phone chưa được

**Comment by giahieu123456** [comment]
- [ ]  chưa search nhân viên theo identify( cmnd/cccd)

**Comment by giahieu123456** [comment]
load payroll fiterType === TIME_SHEET chưa trả về bảng chấm côn
<img width="943" alt="Screen Shot 2022-05-19 at 16 54 22" src="https://user-images.githubusercontent.com/66545389/169266407-fc0c4d1a-b8d9-4b27-9549-7504939dd2fd.png">
g

**Comment by giahieu123456** [comment]
- [ ]  thêm wfh bị lỗi

**Comment by longdratech** [comment]
Chuyển qua issue repo api
